
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: open_flights_development
  username: my_hrms
  password: root12345
  host: localhost
  port: 5432

 

# test:
#   <<: *default
#   database: open_flights_test


production:
  <<: *default
  database: open_flights_production
  username: open_flights
  password: <%= ENV['OPEN_FLIGHTS_DATABASE_PASSWORD'] %>
